{
    "package": {
        "name": "cobra",
        "repo": "rpm",
        "subject": "flatmap",
        "desc": "Proof and Code Presentation Framework",
        "website_url": " http://www.flatmap.net/cobra/",
        "issue_tracker_url": "https://github.com/flatmap/cobra/issues",
        "vcs_url": "https://github.com/flatmap/cobra.git",
        "github_use_tag_release_notes": true,
        "github_release_notes_file": "RELEASE.md",
        "licenses": ["LGPL"],
        "labels": ["presentation","scala","haskell","isabelle"],
        "public_download_numbers": false,
        "public_stats": false
    },
    "version": {
        "name": "version-1.0.4",
        "desc": "Version 1.0.4",
        "vcs_tag": "version-1.0.4",
        "gpgSign": true
    },
    "files":
    [
      {
        "includePattern": "modules/cobra-server/target/rpm/RPMS/noarch/(.*\\.rpm)",
        "uploadPattern": "$1"
      }
    ],
    "publish": true
}